"""UI layer: executable screen and window-behavior designs (PI-002 renders them).

- :mod:`~mentorapp.ui.auth_flows` — login & session UI (WTK-005): the three
  credential screens, the educate-voice outcome messages over the WTK-003
  taxonomy, and the cross-window in-place re-auth controller with
  unsaved-work preservation.
- :mod:`~mentorapp.ui.home_panel` — home panel & admin messaging (WTK-019):
  the REQ-003 screen frame and account menu, startup-preference resolution
  with the broken-pin fallback, the Home dashlet composition, and the
  per-user message center (auto-read on view, explicit acknowledgment,
  urgent banner until read).
- :mod:`~mentorapp.ui.record_preview` — record preview & pop-outs (WTK-021):
  the REQ-012 docked read-only preview that follows the focused grid row,
  real-browser-window pop-outs pinned to their records, the two declared
  actions with never-hide explainers, and the same-user cross-window
  save fan-out.
- :mod:`~mentorapp.ui.shell_header` — standard header, quick-open palette,
  and logout (WTK-026): the REQ-009 header for every window (pop-outs omit
  navigation), the Ctrl+K palette over every reachable panel and view, and
  the user-menu logout seam over the WTK-005 session controller.
"""

from mentorapp.ui.auth_flows import (
    FORGOT_PASSWORD_SCREEN,
    LOGIN_SCREEN,
    REAUTH_PROMPT,
    REAUTH_SCREEN,
    REAUTH_WRONG_USER,
    RESET_REQUESTED,
    SESSION_ENDED,
    SIGN_IN_CRM_UNAVAILABLE,
    SIGN_IN_REJECTED,
    AuthScreen,
    EducateMessage,
    FieldControl,
    InMemorySessionChannel,
    ScreenField,
    SessionLoggedOut,
    SessionRevived,
    UnsavedWorkGuardError,
    WindowPhase,
    WindowSessionController,
    login_failure_message,
)
from mentorapp.ui.home_panel import (
    ACCOUNT_MENU,
    DEFAULT_STARTUP_CHOICE,
    HOME_DASHLETS_PREFERENCE_KEY,
    HOME_FRAME,
    HOME_PANEL_KEY,
    MESSAGES_DASHLET,
    STARTUP_FALLBACK_TO_HOME,
    STARTUP_PREFERENCE_KEY,
    AcknowledgmentNotRequestedError,
    AdminMessage,
    DashletRef,
    HomeFrame,
    MenuItem,
    MessageCenter,
    MessagePriority,
    ResolvedDashlet,
    StartupChoice,
    StartupTarget,
    UnknownMessageError,
    dashlet_unavailable_message,
    resolve_home_dashlets,
    resolve_startup_panel,
)
from mentorapp.ui.record_preview import (
    NO_ROW_FOCUSED,
    OPEN_RECORD_PREVIEW,
    POP_OUT_HAS_NAVIGATION,
    POP_OUT_HEADER_RIGHT,
    POP_OUT_RECORD,
    PREVIEW_DOCK_POSITION,
    RECORD_PREVIEW,
    PanelAction,
    PopOutResult,
    PopOutWindow,
    PreviewContent,
    PreviewPane,
    RecordRef,
    RecordWindows,
    SyncFanout,
    UnknownWindowError,
    already_open_message,
    single_row_required_message,
)
from mentorapp.ui.shell_header import (
    LOGOUT_UNSAVED_WORK,
    MAIN_WINDOW_HEADER,
    POP_OUT_HEADER,
    QUICK_OPEN_SHORTCUT,
    QuickOpenEntry,
    QuickOpenKind,
    StandardHeader,
    header_for_window,
    quick_open_entries,
    request_logout,
    search_quick_open,
)

__all__ = [
    "ACCOUNT_MENU",
    "DEFAULT_STARTUP_CHOICE",
    "FORGOT_PASSWORD_SCREEN",
    "HOME_DASHLETS_PREFERENCE_KEY",
    "HOME_FRAME",
    "HOME_PANEL_KEY",
    "LOGIN_SCREEN",
    "LOGOUT_UNSAVED_WORK",
    "MAIN_WINDOW_HEADER",
    "MESSAGES_DASHLET",
    "NO_ROW_FOCUSED",
    "OPEN_RECORD_PREVIEW",
    "POP_OUT_HAS_NAVIGATION",
    "POP_OUT_HEADER",
    "POP_OUT_HEADER_RIGHT",
    "POP_OUT_RECORD",
    "PREVIEW_DOCK_POSITION",
    "QUICK_OPEN_SHORTCUT",
    "REAUTH_PROMPT",
    "REAUTH_SCREEN",
    "REAUTH_WRONG_USER",
    "RECORD_PREVIEW",
    "RESET_REQUESTED",
    "SESSION_ENDED",
    "SIGN_IN_CRM_UNAVAILABLE",
    "SIGN_IN_REJECTED",
    "STARTUP_FALLBACK_TO_HOME",
    "STARTUP_PREFERENCE_KEY",
    "AcknowledgmentNotRequestedError",
    "AdminMessage",
    "AuthScreen",
    "DashletRef",
    "EducateMessage",
    "FieldControl",
    "HomeFrame",
    "InMemorySessionChannel",
    "MenuItem",
    "MessageCenter",
    "MessagePriority",
    "PanelAction",
    "PopOutResult",
    "PopOutWindow",
    "PreviewContent",
    "PreviewPane",
    "QuickOpenEntry",
    "QuickOpenKind",
    "RecordRef",
    "RecordWindows",
    "ResolvedDashlet",
    "ScreenField",
    "SessionLoggedOut",
    "SessionRevived",
    "StandardHeader",
    "StartupChoice",
    "StartupTarget",
    "SyncFanout",
    "UnknownMessageError",
    "UnknownWindowError",
    "UnsavedWorkGuardError",
    "WindowPhase",
    "WindowSessionController",
    "already_open_message",
    "dashlet_unavailable_message",
    "header_for_window",
    "login_failure_message",
    "quick_open_entries",
    "request_logout",
    "resolve_home_dashlets",
    "resolve_startup_panel",
    "search_quick_open",
    "single_row_required_message",
]
