/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials and open a session; return the opaque reference.
         *
         *     Rejection is the one generic ``invalidCredentials`` 401 regardless of
         *     which credential was wrong; a CRM outage is the distinct
         *     ``crmUnavailable`` 503 — the credentials were never judged, and that
         *     must never read as a wrong password. The refusal is logged without the
         *     login name: a failed login field routinely contains a password typed
         *     into the wrong box, so the attempted identifier never reaches the log
         *     stream.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End the shared session record so every window fails closed (REQ-005).
         *
         *     Always answers the same success envelope: logging out an unknown,
         *     already-rotated, or already-ended reference reveals nothing about which
         *     references exist, and the caller's goal state ("not signed in") holds
         *     either way.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reauth
         * @description Re-authenticate in place: one re-login restores every window (REQ-005).
         *
         *     Serves both the ``reauthRequired`` challenge (revive the expired session,
         *     same identity, rotated secret) and proactive refresh of a still-active
         *     session. Credentials are checked before the session is touched, so the
         *     ``invalidCredentials`` refusal is identical whether or not the reference
         *     is live. A dead session (ended, or grace lapsed) answers the generic
         *     ``unauthenticated`` 401 — fresh login required. Presenting another
         *     user's VALID credentials is the distinct ``reauthIdentityMismatch``
         *     refusal: the session's owner is already on the caller's screen, so the
         *     precise code discloses nothing and the session stays revivable by the
         *     right user.
         */
        post: operations["reauth_auth_reauth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Start a password reset; the answer never says whether the account exists.
         *
         *     The seam forwards to the CRM's own connected recovery flow (see
         *     :class:`ForgotPasswordFlow`); this endpoint's whole contract is the
         *     constant response. Reset links land the recipient on the CRM's own flow,
         *     not app action-token redemption — no app credential or session state
         *     changes here. Only a CRM outage breaks the constant answer (503, which
         *     says nothing about any account).
         */
        post: operations["forgot_password_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/actions/{action_name}/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem Action
         * @description Spend one use of an emailed action link (REQ-007).
         *
         *     The path names the action this call serves and the service refuses a
         *     token minted for any other action — the binding check is server-side,
         *     never client-honored. The response carries no identity: downstream
         *     feature endpoints consume the redeemed record server-side; the link
         *     holder learns only that the action went through and what remains of the
         *     use budget. Refusals are the generic 403 token envelope.
         */
        post: operations["redeem_action_auth_actions__action_name__redeem_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/{entity_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity Schema
         * @description Describe every live field of one entity from the schema registry.
         *
         *     Returns ``data.entityType`` plus ``data.fields`` (ordered by ``fieldName``
         *     for a deterministic contract; display order is the client's job via
         *     ``visibilityHints``). 404 when the entity has no live registry rows —
         *     an entity with zero fields cannot exist, so no-rows means unknown entity.
         */
        get: operations["get_entity_schema_schema__entity_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences/{preference_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Preference
         * @description Resolve one preference document: the caller's own row, else the org default.
         *
         *     Returns ``data.preferenceValue`` plus ``data.preferenceScope``
         *     (``user``/``orgDefault``). 404 when neither row exists — an unset
         *     preference is a normal state the client answers with its built-in default.
         */
        get: operations["get_preference_preferences__preference_key__get"];
        /**
         * Put Preference
         * @description Create or replace the CALLER's preference document for one key.
         *
         *     Always writes the user's own row — the org default is read-time fallback,
         *     never a write target here. Deliberately last-write-wins with no
         *     ``rowVersion`` round-trip: GET may have served the ORG-DEFAULT row while
         *     PUT targets the user's row, so a version carried across that scope
         *     boundary is incoherent — and the document is opaque client state (layouts,
         *     pins) with no field-level merge a 409 dialog could offer; the newest save
         *     is the right one. An unchanged document is a no-op (no version bump).
         */
        put: operations["put_preference_preferences__preference_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Home
         * @description Compose the Home screen: frame, Areas rail, dashlets, and messages.
         *
         *     Rendering the message dashlet READS its messages (REQ-011 auto-read on
         *     view), so ``meta.unreadCount`` reports the badge value this open clears —
         *     a repeat open returns 0. Broken dashlets stay in ``data.dashlets`` with
         *     an educate ``notice``; the messages dashlet is always first. Fails 500
         *     when the catalog/message providers are unwired; 422 without ``X-User-ID``.
         */
        get: operations["get_home_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home/banner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Banner
         * @description Urgent messages this user has NOT read — every panel banners these.
         *
         *     Reading (not acknowledgment) clears a message from here, via ``GET
         *     /home`` or ``POST /home/messages/{key}/read``. ``meta.unreadCount`` is
         *     the header badge: ALL unexpired unread messages, not just urgent ones.
         */
        get: operations["get_banner_home_banner_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description The admin's message corpus: every live message, newest first (WTK-192).
         *
         *     Unlike every user path this INCLUDES expired messages — the admin manages
         *     the corpus and reads acknowledgment reports after expiry. Each record
         *     carries ``rowVersion`` so an edit can round-trip it (DB-S4).
         */
        get: operations["list_messages_home_messages_get"];
        put?: never;
        /**
         * Post Message
         * @description Publish an admin message to every user (REQ-011).
         *
         *     ``postedBy`` is stamped from the acting identity, never taken from the
         *     body — the dashlet's posted-by line must be auditable. Posting rights
         *     ride the admin surface's data-source grant once that catalog is wired
         *     (REQ-006); today the trusted front end is the caller, as everywhere
         *     behind ``X-User-ID``.
         */
        post: operations["post_message_home_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home/messages/{message_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Message
         * @description Soft-delete one message (DB-S3): it leaves every surface immediately.
         *
         *     Receipts are untouched — the acknowledgment audit survives the message,
         *     exactly as it survives expiration.
         */
        delete: operations["delete_message_home_messages__message_key__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Message
         * @description Edit one message under the write contract (DB-S12): PATCH, never PUT.
         *
         *     Only fields present in the request travel to storage; a stale
         *     ``rowVersion`` returns 409 with the current record in ``data``. 404 for
         *     unknown and deleted keys; expired messages stay editable (extending an
         *     expiration is a legitimate admin act).
         */
        patch: operations["patch_message_home_messages__message_key__patch"];
        trace?: never;
    };
    "/home/messages/{message_key}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read Message
         * @description The banner's open-the-message act: render ONE message, which reads it.
         *
         *     Scoped on purpose — opening a banner from another panel must not read
         *     the Home messages the user never saw. 404 for unknown AND expired keys
         *     alike (an expired message has left every surface).
         */
        post: operations["read_message_home_messages__message_key__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home/messages/{message_key}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge Message
         * @description Record this user's EXPLICIT acknowledgment click (REQ-011).
         *
         *     The only path to acknowledged state — no view or banner ever implies it.
         *     Acknowledging also reads (the click sits on the rendered message), so an
         *     urgent banner never outlives an acknowledgment. 422
         *     ``acknowledgmentNotRequested`` when the message never asked — that is a
         *     caller bug, not a user state.
         */
        post: operations["acknowledge_message_home_messages__message_key__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home/messages/{message_key}/acknowledgments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Message Acknowledgments
         * @description The admin audit: who has, and has not, acknowledged one message.
         *
         *     ``userId`` repeats once per roster member — the roster lives in the
         *     admin's user data source, not here, so the caller supplies who should
         *     have acknowledged. Expiration never closes the books: an expired
         *     message answers this audit like a live one.
         */
        get: operations["message_acknowledgments_home_messages__message_key__acknowledgments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{entity_type}/{record_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Record Preview
         * @description The read-optimized content one record window renders (REQ-012).
         *
         *     Serves the flat record (custom attributes merged, ``rowVersion``
         *     included) plus the WTK-021 pane and pop-out-frame declarations. 422
         *     ``unknownEntityType`` for a name the catalog does not know; 404 for a
         *     record that never existed; 200 with ``data.notice`` for a soft-deleted
         *     one (a pinned pop-out must explain, never blank). Fails 500 when the
         *     catalog provider is unwired; 422 without ``X-User-ID``.
         */
        get: operations["get_record_preview_records__entity_type___record_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shell
         * @description Compose the shell: both headers plus the user's rendered navigation.
         *
         *     ``data.mainWindow``/``data.popOut`` carry the one WTK-026 header
         *     declaration for each window kind (pop-outs are record windows, not panel
         *     hosts — REQ-012). ``data.navigation`` renders the stored pin set for its
         *     stored presentation with every pin present and broken ones marked
         *     (REQ-010/REQ-015). Fails 500 when the catalog provider is unwired; 422
         *     without ``X-User-ID``.
         */
        get: operations["get_shell_shell_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shell/quick-open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quick Open
         * @description The Ctrl+K palette: every reachable destination, narrowed by ``q``.
         *
         *     Reachability is the one grant boundary in its quiet form (listing is not
         *     an open attempt); soft-deleted views simply are not destinations. An
         *     empty ``q`` serves the full catalog — panels first, then views, each
         *     alphabetical; a query ranks prefix matches before substring matches.
         */
        get: operations["get_quick_open_shell_quick_open_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shell/navigation/pins/{pin_key}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Navigation Pin
         * @description Activate one pin: its panel with its view active, or the dialog (REQ-015).
         *
         *     Resolution happens now, at click time — a pin that broke after the
         *     navigation was drawn explains itself (``data.dialog``: the educate
         *     message plus the two choices) instead of opening a dead panel; one
         *     repaired since simply opens (``data.opened``). Exactly one of the two is
         *     set. 404 for a pin no longer in the profile.
         */
        post: operations["open_navigation_pin_shell_navigation_pins__pin_key__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shell/bell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bell
         * @description The bell dropdown: the session user's unread entries (REQ-014).
         *
         *     ``meta.unreadCount`` is the badge number — the header may poll this
         *     endpoint for the count alone. Reading does NOT stamp ``readAt``: a GET
         *     stays safe to repeat, and the client acknowledges the view explicitly
         *     via ``POST /shell/bell/read`` when the dropdown opens.
         */
        get: operations["get_bell_shell_bell_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shell/bell/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Bell Read
         * @description Viewing the bell stamps every unread entry (REQ-014).
         *
         *     A versioned update like any other write (DB-S4), never a delete — the
         *     entries stay in the notification table, only the badge predicate stops
         *     matching them. Idempotent: a second view finds nothing unread and stamps
         *     nothing, so ``data.markedRead`` reports what THIS view cleared.
         */
        post: operations["mark_bell_read_shell_bell_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiError
         * @description One structured error entry in ``errors[]``.
         *
         *     ``fieldName`` is the registry field the failure belongs to, or ``None``
         *     for request-level failures (not-found, conflict, internal). ``code`` is
         *     machine-readable and stable; ``message`` is for humans and may change.
         */
        ApiError: {
            /** Fieldname */
            fieldName: string | null;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * Envelope
         * @description The one response shape. Constructed only via ``ok`` and ``fail``.
         */
        Envelope: {
            /** Data */
            data: unknown;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /** Errors */
            errors: components["schemas"]["ApiError"][] | null;
        };
        /**
         * ForgotPasswordBody
         * @description ``POST /auth/forgot-password`` body: identifiers only, never a password.
         *
         *     Both identifiers travel because EspoCRM's ``passwordChangeRequest``
         *     requires the username+email pair — matching WTK-005's
         *     ``FORGOT_PASSWORD_SCREEN``.
         */
        ForgotPasswordBody: {
            /** Loginname */
            loginName: string;
            /** Emailaddress */
            emailAddress: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginBody
         * @description ``POST /auth/login`` body — the only surface where credentials travel.
         */
        LoginBody: {
            /** Loginname */
            loginName: string;
            /** Password */
            password: string;
        };
        /**
         * LogoutBody
         * @description ``POST /auth/logout`` body: the reference whose session ends.
         */
        LogoutBody: {
            /** Sessionreference */
            sessionReference: string;
        };
        /**
         * MessagePatchBody
         * @description PATCH body: only the changed fields plus the mandatory ``rowVersion``.
         */
        MessagePatchBody: {
            /** Rowversion */
            rowVersion: number;
            /** Title */
            title?: string | null;
            /** Body */
            body?: string | null;
            priority?: components["schemas"]["MessagePriority"] | null;
            /** Requiresacknowledgment */
            requiresAcknowledgment?: boolean | null;
            /** Expiresat */
            expiresAt?: string | null;
        };
        /**
         * MessagePostBody
         * @description POST body for publishing one admin message.
         */
        MessagePostBody: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** @default normal */
            priority: components["schemas"]["MessagePriority"];
            /**
             * Requiresacknowledgment
             * @default false
             */
            requiresAcknowledgment: boolean;
            /** Expiresat */
            expiresAt?: string | null;
        };
        /**
         * MessagePriority
         * @enum {string}
         */
        MessagePriority: "normal" | "urgent";
        /**
         * PreferencePutBody
         * @description PUT body: the whole preference document — a partial merge does not exist.
         */
        PreferencePutBody: {
            /** Preferencevalue */
            preferenceValue: {
                [key: string]: unknown;
            };
        };
        /**
         * ReauthBody
         * @description ``POST /auth/reauth`` body: the held reference plus fresh credentials.
         */
        ReauthBody: {
            /** Sessionreference */
            sessionReference: string;
            /** Loginname */
            loginName: string;
            /** Password */
            password: string;
        };
        /**
         * RedeemBody
         * @description ``POST /auth/actions/{action}/redeem`` body: the emailed link token.
         */
        RedeemBody: {
            /** Actiontoken */
            actionToken: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reauth_auth_reauth_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReauthBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeem_action_auth_actions__action_name__redeem_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_schema_schema__entity_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preference_preferences__preference_key__get: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path: {
                preference_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_preference_preferences__preference_key__put: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path: {
                preference_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencePutBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_home_home_get: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_banner_home_banner_get: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_home_messages_get: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_home_messages_post: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessagePostBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_message_home_messages__message_key__delete: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path: {
                message_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_message_home_messages__message_key__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessagePatchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_message_home_messages__message_key__read_post: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path: {
                message_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_message_home_messages__message_key__acknowledge_post: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path: {
                message_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    message_acknowledgments_home_messages__message_key__acknowledgments_get: {
        parameters: {
            query?: {
                userId?: string[] | null;
            };
            header: {
                "X-User-ID": string;
            };
            path: {
                message_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_preview_records__entity_type___record_id__preview_get: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path: {
                entity_type: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shell_shell_get: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quick_open_shell_quick_open_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header: {
                "X-User-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_navigation_pin_shell_navigation_pins__pin_key__open_post: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path: {
                pin_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bell_shell_bell_get: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_bell_read_shell_bell_read_post: {
        parameters: {
            query?: never;
            header: {
                "X-User-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
}
