"""Storage layer — base-entity model, key policy, registries, jobs, and change feed.

Implements the ENG-004 data-model standard: ``entity`` carries the declarative
base, structural system columns, and key-naming policy (WTK-125); ``models``
carries the schema registry, option sets, background jobs, and change feed
(WTK-126/WTK-127); ``auth`` carries users, sessions, action tokens, access
grants, and data sources (WTK-001); ``registry_seed`` seeds built-in registry
rows from the column-site definitions the drift check verifies (WTK-134);
``crm_refs`` carries the CRM reference anchors — the REQ-062 ownership
boundary (WTK-150, reconciled to REQ-086 in PI-010); ``mentoring`` carries
the application-owned mentoring domain — company role subclasses,
engagements, sessions, resources, events (PI-010, WTK-164..175); ``triage``
carries the REQ-072 engagement triage read; ``theming`` carries the
look-and-feel platform entities (PI-007, WTK-111); ``help`` carries the
help-system link mappings and settings singleton (PI-006, WTK-099). One
declarative ``Base`` spans them all.
"""

from mentorapp.storage.adminsql import (
    ADMIN_SQL_ROLE,
    ADMIN_SQL_STATEMENT_TIMEOUT_MS,
    CURRENT_USER_PARAM,
    AdminSqlError,
    AdminSqlSource,
    admin_sql_role_ddl,
    execute_admin_sql,
    validate_admin_sql,
)
from mentorapp.storage.auth import (
    AccessGrant,
    ActionToken,
    AppUser,
    AuthSession,
    DataSource,
    DataSourceRoleGrant,
    LookupSourceBinding,
    TokenAuditEvent,
    UserCrmAccount,
)
from mentorapp.storage.base import StructuralColumnsMixin, as_utc, utcnow
from mentorapp.storage.crm_refs import CrmCompanyRef, CrmMentorRef
from mentorapp.storage.entity import (
    OWNERSHIP_SIDES,
    Base,
    BaseEntity,
    entity_key,
    entity_ref,
    live_index,
    live_unique,
)
from mentorapp.storage.grids import (
    SORT_DIRECTIONS,
    VIEW_TYPES,
    Grid,
    GridDeepLink,
    GridSessionState,
    GridView,
    SortSpec,
)
from mentorapp.storage.help import (
    HELP_SOURCE_TYPES,
    HelpMapping,
    HelpSettings,
    help_settings,
    live_help_mapping,
)
from mentorapp.storage.ids import uuid7, uuid7_created_at
from mentorapp.storage.leadership import (
    engagement_status_counts,
    mentor_activity,
    sessions_held_per_period,
)
from mentorapp.storage.mentoring import (
    ENGAGEMENT_STATUS_OPTION_SET,
    ENGAGEMENT_STATUS_VALUES,
    RESOURCE_KIND_OPTION_SET,
    RESOURCE_KIND_VALUES,
    SESSION_STATUS_OPTION_SET,
    SESSION_STATUS_VALUES,
    Client,
    Engagement,
    Event,
    MentoringSession,
    Partner,
    ProgressGoal,
    Resource,
)
from mentorapp.storage.messages import AdminMessage, AdminMessageReceipt
from mentorapp.storage.models import (
    CHANGE_KINDS,
    JOB_STATUSES,
    NOTIFICATION_TYPES,
    BackgroundJob,
    ChangeFeedEntry,
    DuplicateOverride,
    FieldChange,
    Notification,
    OptionSet,
    OptionValue,
    PostalCode,
    SchemaRegistry,
    UserPreference,
)
from mentorapp.storage.readsurface import (
    STRUCTURAL_COLUMN_NAMES,
    DriftFinding,
    SchemaDriftError,
    generate_read_view_sql,
    partial_index_rule_violations,
    read_view_name,
    regenerate_read_views,
    run_schema_drift_startup_check,
    schema_drift_findings,
)
from mentorapp.storage.registry_seed import (
    BuiltInField,
    RegistrySeedError,
    RegistrySeedResult,
    built_in_field_from_column,
    built_in_fields,
    seed_built_in_registry,
)
from mentorapp.storage.theming import (
    CHROME_COLOR_SLOTS,
    COLOR_SLOTS,
    CONDITION_OPERATORS,
    CONTRAST_GUARDRAIL_BEHAVIORS,
    FONT_SLOTS,
    FORMATTING_EFFECTS,
    LAUNCH_SETS,
    ROW_THEME_COLOR_SLOTS,
    SHARED_TYPE_SCALE_NAME,
    STATUS_COLOR_SLOTS,
    TEMPLATE_TYPES,
    TYPE_SCALE_DEFAULT_SIZES,
    TYPE_SCALE_STEPS,
    ColorTemplate,
    ConditionalFormattingRule,
    TypeScale,
    shared_type_scale,
)
from mentorapp.storage.triage import (
    ENGAGEMENT_TRIAGE_COLUMNS,
    ENGAGEMENT_TRIAGE_FORMATTING_RULES,
    engagement_triage_rows,
    engagement_triage_sql,
)
from mentorapp.storage.workprocess import (
    ACTION_CLASSIFICATIONS,
    RUN_STATE_COMMITTED,
    RUN_STATE_DISCARDED,
    RUN_STATE_IN_FLIGHT,
    RUN_STATES,
    SELECTION_CONTRACTS,
    TERMINAL_RUN_STATES,
    WorkprocessRegistration,
    WorkprocessRegistrationDataSource,
    WorkprocessRun,
    registrations_for_data_source,
)

__all__ = [
    "ACTION_CLASSIFICATIONS",
    "ADMIN_SQL_ROLE",
    "ADMIN_SQL_STATEMENT_TIMEOUT_MS",
    "CHANGE_KINDS",
    "CHROME_COLOR_SLOTS",
    "COLOR_SLOTS",
    "CONDITION_OPERATORS",
    "CONTRAST_GUARDRAIL_BEHAVIORS",
    "CURRENT_USER_PARAM",
    "ENGAGEMENT_STATUS_OPTION_SET",
    "ENGAGEMENT_STATUS_VALUES",
    "ENGAGEMENT_TRIAGE_COLUMNS",
    "ENGAGEMENT_TRIAGE_FORMATTING_RULES",
    "FONT_SLOTS",
    "FORMATTING_EFFECTS",
    "HELP_SOURCE_TYPES",
    "JOB_STATUSES",
    "LAUNCH_SETS",
    "NOTIFICATION_TYPES",
    "OWNERSHIP_SIDES",
    "RESOURCE_KIND_OPTION_SET",
    "RESOURCE_KIND_VALUES",
    "ROW_THEME_COLOR_SLOTS",
    "RUN_STATES",
    "RUN_STATE_COMMITTED",
    "RUN_STATE_DISCARDED",
    "RUN_STATE_IN_FLIGHT",
    "SELECTION_CONTRACTS",
    "SESSION_STATUS_OPTION_SET",
    "SESSION_STATUS_VALUES",
    "SHARED_TYPE_SCALE_NAME",
    "SORT_DIRECTIONS",
    "STATUS_COLOR_SLOTS",
    "STRUCTURAL_COLUMN_NAMES",
    "TEMPLATE_TYPES",
    "TERMINAL_RUN_STATES",
    "TYPE_SCALE_DEFAULT_SIZES",
    "TYPE_SCALE_STEPS",
    "VIEW_TYPES",
    "AccessGrant",
    "ActionToken",
    "AdminMessage",
    "AdminMessageReceipt",
    "AdminSqlError",
    "AdminSqlSource",
    "AppUser",
    "AuthSession",
    "BackgroundJob",
    "Base",
    "BaseEntity",
    "BuiltInField",
    "ChangeFeedEntry",
    "Client",
    "ColorTemplate",
    "ConditionalFormattingRule",
    "CrmCompanyRef",
    "CrmMentorRef",
    "DataSource",
    "DataSourceRoleGrant",
    "DriftFinding",
    "DuplicateOverride",
    "Engagement",
    "Event",
    "FieldChange",
    "Grid",
    "GridDeepLink",
    "GridSessionState",
    "GridView",
    "HelpMapping",
    "HelpSettings",
    "LookupSourceBinding",
    "MentoringSession",
    "Notification",
    "OptionSet",
    "OptionValue",
    "Partner",
    "PostalCode",
    "ProgressGoal",
    "RegistrySeedError",
    "RegistrySeedResult",
    "Resource",
    "SchemaDriftError",
    "SchemaRegistry",
    "SortSpec",
    "StructuralColumnsMixin",
    "TokenAuditEvent",
    "TypeScale",
    "UserCrmAccount",
    "UserPreference",
    "WorkprocessRegistration",
    "WorkprocessRegistrationDataSource",
    "WorkprocessRun",
    "admin_sql_role_ddl",
    "as_utc",
    "built_in_field_from_column",
    "built_in_fields",
    "engagement_status_counts",
    "engagement_triage_rows",
    "engagement_triage_sql",
    "entity_key",
    "entity_ref",
    "execute_admin_sql",
    "generate_read_view_sql",
    "help_settings",
    "live_help_mapping",
    "live_index",
    "live_unique",
    "mentor_activity",
    "partial_index_rule_violations",
    "read_view_name",
    "regenerate_read_views",
    "registrations_for_data_source",
    "run_schema_drift_startup_check",
    "schema_drift_findings",
    "seed_built_in_registry",
    "sessions_held_per_period",
    "shared_type_scale",
    "utcnow",
    "uuid7",
    "uuid7_created_at",
    "validate_admin_sql",
]
