"""Storage layer — base-entity model, key policy, registries, jobs, and change feed.

Implements the ENG-004 data-model standard: ``entity`` carries the declarative
base, structural system columns, and key-naming policy (WTK-125); ``models``
carries the schema registry, option sets, background jobs, and change feed
(WTK-126/WTK-127); ``auth`` carries users, sessions, action tokens, access
grants, and data sources (WTK-001); ``registry_seed`` seeds built-in registry
rows from the column-site definitions the drift check verifies (WTK-134);
``crm_refs`` carries the CRM reference anchors — the REQ-062 ownership
boundary (WTK-150); ``mentoring`` carries the application-owned
mentoring-process entities (REQ-063, WTK-156); ``theming`` carries the
look-and-feel platform entities (PI-007, WTK-111). One declarative ``Base``
spans them all.
"""

from mentorapp.storage.adminsql import (
    ADMIN_SQL_ROLE,
    ADMIN_SQL_STATEMENT_TIMEOUT_MS,
    CURRENT_USER_PARAM,
    AdminSqlError,
    AdminSqlSource,
    admin_sql_role_ddl,
    execute_admin_sql,
    validate_admin_sql,
)
from mentorapp.storage.auth import (
    AccessGrant,
    ActionToken,
    AppUser,
    AuthSession,
    DataSource,
    DataSourceRoleGrant,
    TokenAuditEvent,
    UserCrmAccount,
)
from mentorapp.storage.base import StructuralColumnsMixin, as_utc, utcnow
from mentorapp.storage.crm_refs import CrmClientRef, CrmEngagementRef, CrmMentorRef
from mentorapp.storage.entity import (
    OWNERSHIP_SIDES,
    Base,
    BaseEntity,
    entity_key,
    entity_ref,
    live_index,
    live_unique,
)
from mentorapp.storage.grids import (
    SORT_DIRECTIONS,
    VIEW_TYPES,
    Grid,
    GridDeepLink,
    GridSessionState,
    GridView,
    SortSpec,
)
from mentorapp.storage.ids import uuid7, uuid7_created_at
from mentorapp.storage.mentoring import MeetingNote, NextStep, ProgressGoal, SessionLog
from mentorapp.storage.messages import AdminMessage, AdminMessageReceipt
from mentorapp.storage.models import (
    CHANGE_KINDS,
    JOB_STATUSES,
    NOTIFICATION_TYPES,
    SELECTION_CONTRACTS,
    BackgroundJob,
    ChangeFeedEntry,
    DuplicateOverride,
    FieldChange,
    Notification,
    OptionSet,
    OptionValue,
    PostalCode,
    SchemaRegistry,
    UserPreference,
    WorkprocessRegistration,
)
from mentorapp.storage.readsurface import (
    STRUCTURAL_COLUMN_NAMES,
    DriftFinding,
    SchemaDriftError,
    generate_read_view_sql,
    partial_index_rule_violations,
    read_view_name,
    regenerate_read_views,
    run_schema_drift_startup_check,
    schema_drift_findings,
)
from mentorapp.storage.registry_seed import (
    BuiltInField,
    RegistrySeedError,
    RegistrySeedResult,
    built_in_field_from_column,
    built_in_fields,
    seed_built_in_registry,
)
from mentorapp.storage.theming import (
    CHROME_COLOR_SLOTS,
    COLOR_SLOTS,
    CONDITION_OPERATORS,
    CONTRAST_GUARDRAIL_BEHAVIORS,
    FONT_SLOTS,
    FORMATTING_EFFECTS,
    LAUNCH_SETS,
    ROW_THEME_COLOR_SLOTS,
    SHARED_TYPE_SCALE_NAME,
    STATUS_COLOR_SLOTS,
    TEMPLATE_TYPES,
    TYPE_SCALE_DEFAULT_SIZES,
    TYPE_SCALE_STEPS,
    ColorTemplate,
    ConditionalFormattingRule,
    TypeScale,
    shared_type_scale,
)

__all__ = [
    "ADMIN_SQL_ROLE",
    "ADMIN_SQL_STATEMENT_TIMEOUT_MS",
    "CHANGE_KINDS",
    "CHROME_COLOR_SLOTS",
    "COLOR_SLOTS",
    "CONDITION_OPERATORS",
    "CONTRAST_GUARDRAIL_BEHAVIORS",
    "CURRENT_USER_PARAM",
    "FONT_SLOTS",
    "FORMATTING_EFFECTS",
    "JOB_STATUSES",
    "LAUNCH_SETS",
    "NOTIFICATION_TYPES",
    "OWNERSHIP_SIDES",
    "ROW_THEME_COLOR_SLOTS",
    "SELECTION_CONTRACTS",
    "SHARED_TYPE_SCALE_NAME",
    "SORT_DIRECTIONS",
    "STATUS_COLOR_SLOTS",
    "STRUCTURAL_COLUMN_NAMES",
    "TEMPLATE_TYPES",
    "TYPE_SCALE_DEFAULT_SIZES",
    "TYPE_SCALE_STEPS",
    "VIEW_TYPES",
    "AccessGrant",
    "ActionToken",
    "AdminMessage",
    "AdminMessageReceipt",
    "AdminSqlError",
    "AdminSqlSource",
    "AppUser",
    "AuthSession",
    "BackgroundJob",
    "Base",
    "BaseEntity",
    "BuiltInField",
    "ChangeFeedEntry",
    "ColorTemplate",
    "ConditionalFormattingRule",
    "CrmClientRef",
    "CrmEngagementRef",
    "CrmMentorRef",
    "DataSource",
    "DataSourceRoleGrant",
    "DriftFinding",
    "DuplicateOverride",
    "FieldChange",
    "Grid",
    "GridDeepLink",
    "GridSessionState",
    "GridView",
    "MeetingNote",
    "NextStep",
    "Notification",
    "OptionSet",
    "OptionValue",
    "PostalCode",
    "ProgressGoal",
    "RegistrySeedError",
    "RegistrySeedResult",
    "SchemaDriftError",
    "SchemaRegistry",
    "SessionLog",
    "SortSpec",
    "StructuralColumnsMixin",
    "TokenAuditEvent",
    "TypeScale",
    "UserCrmAccount",
    "UserPreference",
    "WorkprocessRegistration",
    "admin_sql_role_ddl",
    "as_utc",
    "built_in_field_from_column",
    "built_in_fields",
    "entity_key",
    "entity_ref",
    "execute_admin_sql",
    "generate_read_view_sql",
    "live_index",
    "live_unique",
    "partial_index_rule_violations",
    "read_view_name",
    "regenerate_read_views",
    "run_schema_drift_startup_check",
    "schema_drift_findings",
    "seed_built_in_registry",
    "shared_type_scale",
    "utcnow",
    "uuid7",
    "uuid7_created_at",
    "validate_admin_sql",
]
